### ISSUE TITLE
Input data format

### ISSUE THREAD

**Issue by gandroz** [common-voice/commonvoice-fr#146]
Je voulais juste savoir si lors de l'inference avec un client python il y avait un format de donnees particulier pour l'input ?
Je passe au modele un vecteur en integer 16bits echantillonne a 16kHz. Est-ce qu'il y a un travail de normalisation a faire avant d'effectuer l'inference ? Est-ce en float ou en integer c'est bon ?
Les premiers resultats que j'ai c'est un peu n'importe quoi, dependamment de la taille du vecteur (1s, 2s etc) je n'ai pas du tout le meme resultat, et il n'y a quasiment aucun mot qui est correctement transcrit. Bref, je sais que c'est tres experiemental, mais sur mon audio c'est vraiment pas terrible, alors je fouille du cote du data en entree, des fois que ce soit ca le probleme

**Comment by lissyx** [comment]
Tu peux regarder le code du client python de base : https://github.com/mozilla/DeepSpeech/blob/master/native_client/python/client.py#L151

**Comment by gandroz** [comment]
Merci, c'est exactement ce que j'ai fait, mais ça ne me dit pas plus
comment est formatter la donnée à la base. Le fichier wav pourrait très
bien être normalisé, et sauvegardé. Ceci dit c'est bien des integer 16bits
en effet.

**Comment by lissyx** [comment]
> Le fichier wav pourrait très bien être normalisé, et sauvegardé.

le format wav a quelques entêtes normalisés, mais plein d'outils respectent pas complètement, et les entêtes on s'en fou pour l'inférence.

et côté donnée, y'a plein de formats différents aussi, et le format dépend de ce qui a été utilisé pour entraîner le modèle, mais pour le moment partout on utilise celui que j'ai indiqué.
