### ISSUE TITLE
Use MLS dataset

### ISSUE THREAD

**Issue by lissyx** [common-voice/commonvoice-fr#150]
Advertised for ~1300h of french: https://arxiv.org/abs/2012.03411

**Comment by lissyx** [comment]
Depends: https://github.com/mozilla/DeepSpeech/pull/3493

**Comment by CapitainFlam** [comment]
Shouldn't this issue be closed now ? It seems to be merged in feb 22 😄

**Comment by wasertech** [comment]
I won’t repeat myself on the other thread so take this as a general response.

Yes most of the work has been done, and yes it has been merged for a long time but inside the coqui/STT project which commonvoice/commonvoice-fr dont uses (still on DeepSpeech which has been depreciated for a while now). My fork of commvoice-fr is more up to date (uses STT and commonvoice 9.0). Checkout the state of it with #163

**Comment by lissyx** [comment]
https://github.com/coqui-ai/STT/commit/f489cccb2bb610a047f23496b6aab5211d8174c4
