### ISSUE TITLE
Error using `kenlm.scorer` with `ctcdecode.CTCBeamDecoder`

### ISSUE THREAD

**Issue by etiennekintzler** [common-voice/commonvoice-fr#154]
I am using a [wav2vec model](https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-french) with a KenLM language model on top for ASR purpose. 

I am using the package `ctcdecode` (see: https://github.com/parlance/ctcdecode) to do a BEAM search with the KenLM. It works well when I trained my own KenLM (in text/arpa file or binary) but it breaks when I use the `kenlm.scorer` available in [fr-fr.zip](https://github.com/common-voice/commonvoice-fr/releases/download/fr-v0.6/fr-fr.zip) in the last release (0.6).

```python
decoder = ctcdecode.CTCBeamDecoder(
    model_path='/path/to/dir/kenlm.scorer',
    labels=vocab_list,
    blank_id=vocab_list.index("<pad>"),
)
```
where vocab_list are the tokens used in https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-french/blob/main/vocab.json

The error I get :

```python
RuntimeError: third_party/kenlm/lm/model.cc:70 in lm::ngram::detail::GenericModel<Search, VocabularyT>::GenericModel(const char*, const lm::ngram::Config&) [with Search = lm::ngram::trie::TrieSearch<lm::ngram::SeparatelyQuantize, lm::ngram::trie::ArrayBhiksha>; VocabularyT = lm::ngram::SortedVocabulary] threw FormatLoadException because `new_config.enumerate_vocab && !parameters.fixed.has_vocabulary'.
The decoder requested all the vocabulary strings, but this binary file does not have them.  You may need to rebuild the binary file with an updated version of build_binary.
```

Are you familiar with this error ? Maybe I should post the issue on `ctcdecode` as well.

**Comment by lissyx** [comment]
I'm not sure what you are trying to achieve, the packaged scorer we ship is only intended to use by DeepSpeech (or Coqui)'s ctcdecoder code: https://pypi.org/project/ds-ctcdecoder/ https://pypi.org/project/coqui-stt-ctcdecoder/

**Comment by dzorlu** [comment]
I am curious if you have found a solution around this @etiennekintzler . I am running into the same issue and came across the thread.
