### ISSUE TITLE
Textes sur Framabook 

### ISSUE THREAD

**Issue by pinage404** [Common-Voice/commonvoice-fr#32]
Framabook héberge quelques textes sous licence CC0 ([Exemple](https://framabook.org/apolog-le-cycle-des-noenautesiii/))

Ils pourraient etre utilisés pour enrichir le corpus de texte

 - [ ] Écriture d'un parseur ePub ?
 - [ ] Extraction de textes
 - [ ] Validation contre un alphabet existant

**Comment by lissyx** [comment]
Je sais que @goofy-mdn en a importé certains, et maintenant tout le monde peut le faire avec Sentence Collector :-).

https://common-voice.github.io/sentence-collector/#/

@pinage404 Est-ce qu'il y a un besoin d'un outil pour aider à leur extraction ?

**Comment by pinage404** [comment]
je ne sais pas

mais un outil pourrait accélérer en automatisant l'extraction

**Comment by lissyx** [comment]
> mais un outil pourrait accélérer en automatisant l'extraction

Patches welcome :)

**Comment by Framartin** [comment]
Je veux bien m'en occuper :)

**Comment by lissyx** [comment]
Tu es le bienvenu, n'hésite pas !
