### ISSUE TITLE
Download the dataset automatically

### ISSUE THREAD

**Issue by Mte90** [Common-Voice/commonvoice-fr#55]
I am trying to do the italian version but (a part that the readme are in french) it is not clear for me how the dataset are downloaded.
The script include different import from different dataset but no url to download automatically them.
It is possible to add that? or at least instructions? in this way setupping is easier.

**Comment by lissyx** [comment]
>  The script include different import from different dataset but no url to download automatically them.

Datasets that allows automatic downloads should already be working. Can you be more specific ?
For example, Common Voice cannot.

> I am trying to do the italian version but (a part that the readme are in french)

Yes, because we have some contributors who are not at ease with english, so I took the decision that `README.md` would be for instructions, in french and `CONTRIBUTING.md` would be for use-case like yours, in english.

**Comment by lissyx** [comment]
@Mte90 The two other datasets that we are using, Lingua Libre and Training Speech, should be able to automatically download their data (and they did the last time I ran them). It's part of the DeepSpeech importer themselves, indeed.

**Comment by lissyx** [comment]
https://github.com/Common-Voice/commonvoice-fr/blob/master/DeepSpeech/Dockerfile.train.fr#L5 gives you a sha1: https://github.com/mozilla/DeepSpeech/blob/df5545299e748aa272d92a0bdfa2cb51fd198528/bin/import_lingua_libre.py#L41

**Comment by lissyx** [comment]
@Mte90 I don't really know if / how this should be better documented, so any PR that augments `CONTRIBUTING.md` that you feel necessary is welcome.

**Comment by Mte90** [comment]
It wasn't clear that deepspeech automatically downloads them, looking at https://github.com/Common-Voice/commonvoice-fr/blob/master/DeepSpeech/import_lingualibre.sh or https://github.com/Common-Voice/commonvoice-fr/blob/master/DeepSpeech/import_trainingspeech.sh refer to packages that are not downloaded somewhere.

It is not clear to me how to adapt this suite to change the language without hardcoding stuff and information about this little things.

**Comment by lissyx** [comment]
> It wasn't clear that deepspeech automatically downloads them, looking at https://github.com/Common-Voice/commonvoice-fr/blob/master/DeepSpeech/import_lingualibre.sh or https://github.com/Common-Voice/commonvoice-fr/blob/master/DeepSpeech/import_trainingspeech.sh refer to packages that are not downloaded somewhere.

Sure. I'm all for improving docs :-)



> It is not clear to me how to adapt this suite to change the language without hardcoding stuff and information about this little things.

Well, I guess it might be fine to hardcode, or doing something smarter. I'm really open to any suggestions, what dataset do you need ?

**Comment by Mte90** [comment]
I think that if there is a config file with all the various parameters like languages or hash this can simplify a lot the adoption of this suite.

**Comment by lissyx** [comment]
> I think that if there is a config file with all the various parameters like languages or hash this can simplify a lot the adoption of this suite.

Again, I'm all open to PR if you have time, I have to focus on other more urgent things right now so I can't fix it asap :)

**Comment by lissyx** [comment]
@Mte90 I'm not forgetting about this, but I have not ahd any time to be able to work on that codebase since, between the heat wave that made me unable to run anything GPU intensive (35°C in the room where I have my desk ...), moving houses, etc. I still am unable to perform training because network in the new house is still temporary.

**Comment by lissyx** [comment]
I think this can be closed now.
